/*
* generated by Xtext
*/
package fr.obeo.dsl.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractSPrototyperJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(fr.obeo.dsl.sPrototyper.SPrototyperPackage.eINSTANCE);
		return result;
	}

}
