/*
* generated by Xtext
*/
package fr.obeo.dsl.ui.contentassist;

import fr.obeo.dsl.ui.contentassist.AbstractSPrototyperProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SPrototyperProposalProvider extends AbstractSPrototyperProposalProvider {

}
