<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sPrototyper" nsURI="http://www.obeo.fr/dsl/SPrototyper" nsPrefix="sPrototyper">
  <eClassifiers xsi:type="ecore:EClass" name="SPrototyper">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewpoints" upperBound="-1"
        eType="#//SPViewpoint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SPViewpoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortcut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceClass" upperBound="-1"
        eType="#//JavaServiceClassReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representations" upperBound="-1"
        eType="#//SPRepresentation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SPRepresentation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SPTable" eSuperTypes="#//SPRepresentation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usages" upperBound="-1"
        eType="#//MetamodelUsage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//TableElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//TableProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recursive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClass" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//SPExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creatable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createExpression" eType="#//RequestOrCreateExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subElements" upperBound="-1"
        eType="#//TableElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//SPExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SPDiagram" eSuperTypes="#//SPRepresentation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metamodels" upperBound="-1"
        eType="#//MetamodelUsage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="root" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//DiagramElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creatable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//SPExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container" eSuperTypes="#//DiagramElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recursive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containerType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="style" eType="#//ContainerStyleDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//DiagramElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerStyleDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//ContainerColorDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//LabelStyleDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="border" eType="#//BorderStyleDefinition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerColorDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//DiagramElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="style" eType="#//NodeStyleDefinition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeStyleDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//SolidColorDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//LabelStyleDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="border" eType="#//BorderStyleDefinition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolidColorDefinition" eSuperTypes="#//ContainerColorDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//Color"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GradientColorDefinition" eSuperTypes="#//ContainerColorDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//Color"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//Color" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabelStyleDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//SPExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//SolidColorDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="italic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BorderStyleDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//SolidColorDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SPExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestExpression" eSuperTypes="#//SPExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="RequestOrCreateExpression" eSuperTypes="#//SPExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="AcceleoExpression" eSuperTypes="#//RequestOrCreateExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="VarRef" eSuperTypes="#//RequestExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureRef" eSuperTypes="#//RequestExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceRef" eSuperTypes="#//RequestOrCreateExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="MetamodelUsage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usage" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaServiceClassReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="javaClass" eType="ecore:EClass platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Color"/>
  <eClassifiers xsi:type="ecore:EClass" name="PreDefinedColorDefinition" eSuperTypes="#//Color">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//PreDefinedColor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PreDefinedColor">
    <eLiterals name="WHITE" literal="white"/>
    <eLiterals name="BLACK" value="1" literal="black"/>
    <eLiterals name="BLUE" value="2" literal="blue"/>
    <eLiterals name="LIGHT_BLUE" value="3" literal="light blue"/>
    <eLiterals name="DARK_BLUE" value="4" literal="dark blue"/>
    <eLiterals name="CHOCOLATE" value="5" literal="chocolate"/>
    <eLiterals name="LIGHT_CHOCOLATE" value="6" literal="light chocolate"/>
    <eLiterals name="DARK_CHOCOLATE" value="7" literal="dark chocolate"/>
    <eLiterals name="GRAY" value="8" literal="gray"/>
    <eLiterals name="LIGHT_GRAY" value="9" literal="light gray"/>
    <eLiterals name="DARK_GRAY" value="10" literal="dark gray"/>
    <eLiterals name="GREEN" value="11" literal="green"/>
    <eLiterals name="LIGHT_GREEN" value="12" literal="light green"/>
    <eLiterals name="DARK_GREEN" value="13" literal="dark green"/>
    <eLiterals name="ORANGE" value="14" literal="orange"/>
    <eLiterals name="LIGHT_ORANGE" value="15" literal="light orange"/>
    <eLiterals name="DARK_ORANGE" value="16" literal="dark orange"/>
    <eLiterals name="PURPLE" value="17" literal="purple"/>
    <eLiterals name="LIGHT_PURPLE" value="18" literal="light purple"/>
    <eLiterals name="DARK_PURPLE" value="19" literal="dark purple"/>
    <eLiterals name="RED" value="20" literal="red"/>
    <eLiterals name="LIGHT_RED" value="21" literal="light red"/>
    <eLiterals name="DARK_RED" value="22" literal="dark red"/>
    <eLiterals name="YELLOW" value="23" literal="yellow"/>
    <eLiterals name="LIGHT_YELLOW" value="24" literal="light yellow"/>
    <eLiterals name="DARK_YELLOW" value="25" literal="dark yellow"/>
  </eClassifiers>
</ecore:EPackage>
