/**
 * generated by Xtext
 */
package fr.obeo.dsl.generator;

@SuppressWarnings("all")
public class SPrototyperGenerator /* implements IGenerator  */{
  public void doGenerate(final /* Resource */Object resource, final /* IFileSystemAccess */Object fsa) {
  }
}
