/*
 * generated by Xtext
 */
package fr.obeo.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SPrototyperRuntimeModule extends fr.obeo.dsl.AbstractSPrototyperRuntimeModule {


}
