/*
* generated by Xtext
*/
package fr.obeo.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SPrototyperOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
