/*
* generated by Xtext
*/
package fr.obeo.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.obeo.dsl.services.SPrototyperGrammarAccess;

public class SPrototyperParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SPrototyperGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.obeo.dsl.parser.antlr.internal.InternalSPrototyperParser createParser(XtextTokenStream stream) {
		return new fr.obeo.dsl.parser.antlr.internal.InternalSPrototyperParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "SPrototyper";
	}
	
	public SPrototyperGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SPrototyperGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
